"""Init

Revision ID: 84e78ed5578c
Revises: 8c790270bb77
Create Date: 2023-04-30 22:40:31.994757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e78ed5578c'
down_revision = '8c790270bb77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
